# Generated by Django 5.1.3 on 2024-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="emotion",
            field=models.CharField(max_length=100),
        ),
    ]
