# Generated by Django 5.1.3 on 2024-12-03 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_or_emotion", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tweet",
        ),
    ]
