# Generated by Django 5.2.1 on 2025-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField()),
                ('sentiment', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3)),
                ('emotion', models.CharField(choices=[('LOVE', 'Love'), ('HAP', 'Happiness'), ('SAD', 'Sadness'), ('WOR', 'Worry')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
